### ISSUE TITLE
Consider renaming Section 5.4 from "Expectation and Impact Classes" to something else

### ISSUE THREAD

**Issue by adammontville** [CISecurity/ROLIE#10]
*Expectation* and *Impact* classes are IODEF-specific, and we may want to create a much broader set of categories.  Maybe we rename from "Expectation and Impact Classes" to "Security Workflow and Task Categories" or something similar.

**Comment by stephenbanghart** [comment]
I agree that it doesn't quite fit in the document anymore. This entire section will probably be moved into the CSIRT document alongside the rest of the IODEF information.

**Comment by adammontville** [comment]
If this moves, then would we still need to consider it as part of #11 (IANA Considerations Discussion)?

**Comment by stephenbanghart** [comment]
Resolved by #13
