### ISSUE TITLE
IdNits Errors in Code segments

### ISSUE THREAD

**Issue by stephenbanghart** [CISecurity/ROLIE#17]
All formatting issues were resolved except for the code segment sections in the non-normative examples. These code segments range from 2 characters to 72 characters over the 72 character line limit.

Do we split them up across multiple lines, or is there a another protocol for dealing with artwork/code segments and line length?

**Comment by adammontville** [comment]
I think we're going to have to split them across lines.  Even if you handle the spacing differently.  Try something like having the element label on one line with any attributes on lines below, something like this (if the formatting comes up):
  <link
     href="http://www.example.org/csirt/private/incidents/123456"
     rel="alternate"
     type="xml"
  />
Then, we can consider getting rid of the comments that seem superfluous (assuming they're sufficiently covered in the text).
I also think we need to handle the leading white space differently.  It looks like you can pull most of those long examples in by at least three spaces.
I can try to see what I can whip up real quick.

**Comment by adammontville** [comment]
Clearly, the formatting didn't really work well...

**Comment by adammontville** [comment]
Just published a change, hope it helps in some way.

**Comment by stephenbanghart** [comment]
Folded in changes from the readability patch in most recent commit. Almost all Idnits errors resolved, some changes may need to be made to enhance clarity of reformatted code segments.

**Comment by stephenbanghart** [comment]
Resolved with previous fixes.
