### ISSUE TITLE
Remove the HTTP methods section?

### ISSUE THREAD

**Issue by david-waltermire-nist** [CISecurity/ROLIE#23]
This section is somewhat disconnected from the content it references in the ATOMPub specification in [RFC5023 section 5](https://tools.ietf.org/html/rfc5023#section-5.5). These protocol operations, with the exception of "PATCH", are addressed there already. Do we need to keep this section?

**Comment by stephenbanghart** [comment]
I agree that the section is not needed. I'll fold this change into my Atom Requirements branch.

**Comment by stephenbanghart** [comment]
Change implemented in Atom Req branch merge.
