### ISSUE TITLE
Data Model Enumeration

### ISSUE THREAD

**Issue by stephenbanghart** [CISecurity/ROLIE#30]
The current ROLIE core specifies that both information-types and the data models (formats) will be explicitly listed in the IANA table. Should the IANA table only list information-types, leaving the data-model as an open choice, or should we continue to list the "officially supported" data models?

**Comment by stephenbanghart** [comment]
This was discussed at the IETF 96 MILE WG meeting. Roman Danyliw suggested that we enumerate the data models supported by a given information type. An open-world approach should be taken, allowing private extensions to be used. We need to work out a mechanism to support this, and propose the solution to the list.

**Comment by athiasjerome** [comment]
I agree with the suggestion

**Comment by stephenbanghart** [comment]
Some material should be put together to discuss options on the list, if needed more can be discussed at IETF 97.

**Comment by stephenbanghart** [comment]
After MILE IETF97, it was decided by the WG that formats can be listed by the extension documents, but will not be registered, allowing for an open world approach. This is officially documented in version -06
