### ISSUE TITLE
Authentication and Authorization Methods

### ISSUE THREAD

**Issue by stephenbanghart** [CISecurity/ROLIE#34]
Related to issue #9.

Authentication and authorization can be handled using a number of different mechanisms, for this reason its not clear if we can require a specific mechanism in the ROLIE core. More discussion is needed with the working group to determine a way forward. 

Proposals:
- A: Select one or more authentication and authorization mechanisms as MTI
- B:  Address these issues in separate drafts.

**Comment by johnpfield** [comment]
I think a separate draft for authentication and authorization issues would make sense.  In general, it would be reasonable to factor this out, as the choice to use the ROLIE interface would be independent of how to authenticate.  We should allow the choice of mechanism to be a deployment-dependent decision.  e.g., OAUTH2 may make sense for interactive end users doing browser-based interactions who need to establish a session, while mutual TLS might be more appropriate for inter-system scenarios such as a CI/CD pipeline, and so on.

**Comment by stephenbanghart** [comment]
Based on input on this issue from the mailing list, interest seems focused on option B. In the absence of any objections, we will pursue option B moving forward.
