### ISSUE TITLE
Reconsider use of "cyber" in most cases

### ISSUE THREAD

**Issue by adammontville** [CISecurity/ROLIE#7]
There was recently a DISCUSS entered on 5070bis around use of the term "cyber".  The general feel in the IESG (and with both security ADs) is that it's a marketing term that should probably be removed under most circumstances.  This issue is based on reading of the ROLIE draft, but may apply to the informational draft as well.

**Comment by david-waltermire-nist** [comment]
Was there a suggestion of what to replace "cyber security information sharing" with? We are sharing operational cybersecurity information or security automation information. Should it be changed to security automation information sharing?

**Comment by adammontville** [comment]
Yeah s/cyber//g

I think the idea is that we're primarily concerned with information technology, and that is implicit in the fact that we intend to draft specifications and standards in the IETF.  Where we need to explicitly distinguish between information technology and physical systems, then we can probably use "cyber-physical systems" or something similar.

I don't like "cyber" any more than they do, to be honest.  In the context of ROLIE, we're sharing security automation information. ??

**Comment by stephenbanghart** [comment]
Resolved in #14 and recent commit.
