### ISSUE TITLE
Should we recommend OAUTH as an authentication mechanism?

### ISSUE THREAD

**Issue by adammontville** [CISecurity/ROLIE#9]
If we're broadening the use of ROLIE, we may not have people connecting all the time, but we'll have that app-to-app sort of connection and OAUTH feels like something we should consider explicitly mentioning.

**Comment by david-waltermire-nist** [comment]
We probably need to discuss how to address client and user authentication. I wonder at this point if a single solution will be enough. We should probably talk about this on the list. We may need to get some outside expertise from HTTP auth experts as well.

**Comment by stephenbanghart** [comment]
The original draft recommended XACML, that write up is found under section 5 in the CSIRT document. It seems that we should probably recommend at least one solution.

**Comment by adammontville** [comment]
This, like software identification, has a lot of different solutions available.  I agree with Dave that we should have a discussion on the list about this.  We should clearly recognize the requirements here--it's not just people that are going to be accessing these services, but software fulfilling some workflow.  Consider the SACM vulnerability assessment flow.  ROLIE could provide the repository for vulnerability description data, and I'm sure that people aren't going to be the ones logging in.

**Comment by stephenbanghart** [comment]
Adding that we should discuss XACML and http-auth as well.

**Comment by stephenbanghart** [comment]
Resolved via #34
